# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whodunnit < Formula
  desc "Tool for counting and blaming lines in a repo."
  homepage "https://github.com/connorgannaway/whodunnit"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.1.4/whodunnit_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "08684c81229a5870aaca6dc48ffa0717c2ac17d87f47a4306621a03957f4cf66"

      def install
        bin.install "whodunnit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/connorgannaway/whodunnit/releases/download/v0.1.4/whodunnit_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "153bf05496096efdc94f14f39054baf0554709e95d220e392bd92a8bc7da0dff"

      def install
        bin.install "whodunnit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/connorgannaway/whodunnit/releases/download/v0.1.4/whodunnit_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "e785bd0b40b7857297c7c968e316bf1ea896f82ad34e9390f60cafc3fb604fc6"

        def install
          bin.install "whodunnit"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/connorgannaway/whodunnit/releases/download/v0.1.4/whodunnit_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "4d70f3529eaa277d423349296133bef4913415ac8d05326e8acc563037a6bfb8"

        def install
          bin.install "whodunnit"
        end
      end
    end
  end
end
